// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BigQueryDAL is an autogenerated mock type for the BigQueryDAL type
type BigQueryDAL struct {
	mock.Mock
}

// CheckViewExists provides a mock function with given fields: ctx, cloud, customerID
func (_m *BigQueryDAL) CheckViewExists(ctx context.Context, cloud string, customerID string) (bool, error) {
	ret := _m.Called(ctx, cloud, customerID)

	if len(ret) == 0 {
		panic("no return value specified for CheckViewExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, cloud, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, cloud, customerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, cloud, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBigQueryDAL creates a new instance of BigQueryDAL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBigQueryDAL(t interface {
	mock.TestingT
	Cleanup(func())
}) *BigQueryDAL {
	mock := &BigQueryDAL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
