// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Converter is an autogenerated mock type for the Converter type
type Converter struct {
	mock.Mock
}

// Convert provides a mock function with given fields: from, to, amount, date
func (_m *Converter) Convert(from string, to string, amount float64, date time.Time) (float64, error) {
	ret := _m.Called(from, to, amount, date)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string, string, float64, time.Time) float64); ok {
		r0 = rf(from, to, amount, date)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, float64, time.Time) error); ok {
		r1 = rf(from, to, amount, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewConverter interface {
	mock.TestingT
	Cleanup(func())
}

// NewConverter creates a new instance of Converter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConverter(t mockConstructorTestingTNewConverter) *Converter {
	mock := &Converter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
