// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CreditServiceMock is an autogenerated mock type for the Service type
type CreditServiceMock struct {
	mock.Mock
}

// HandleCustomerCredits provides a mock function with given fields: ctx, customerID
func (_m *CreditServiceMock) HandleCustomerCredits(ctx context.Context, customerID string) error {
	ret := _m.Called(ctx, customerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCreditServiceMock creates a new instance of CreditServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreditServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreditServiceMock {
	mock := &CreditServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
