// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	session "github.com/aws/aws-sdk-go/aws/session"
	mock "github.com/stretchr/testify/mock"
)

// AssumedSession is an autogenerated mock type for the AssumedSession type
type AssumedSession struct {
	mock.Mock
}

// GetAssumedSessionForAccount provides a mock function with given fields: accountID
func (_m *AssumedSession) GetAssumedSessionForAccount(accountID string) (*session.Session, error) {
	ret := _m.Called(accountID)

	var r0 *session.Session
	if rf, ok := ret.Get(0).(func(string) *session.Session); ok {
		r0 = rf(accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
