Description: This template creates a Cross-Account-Role that will grant Doit CMP permissions to your AWS account
Parameters:
  RoleToAddPolicyTo:
    Type: String
    Description: Role to add the policy to
  Core:
    Description: Add core policy.
    Default: true
    Type: String
    AllowedValues:
      - true
  Spot0:
    Description: Add spot policy.
    Default: false
    Type: String
    AllowedValues:
      - false
      - true
  Quotas:
    Description: Add Quotas policy.
    Default: false
    Type: String
    AllowedValues:
      - false
      - true
  ExternalId:
    Type: String
    Description: External ID for Cross-Account-Role
  NotificationUrl:
    Type: String
    Description: URL used for notification (must end in /api/)
Conditions:
  CreateCoreResources: !Equals
    - !Ref Core
    - true
  CreateSpot0Resources: !Equals
    - !Ref Spot0
    - true
  CreateQuotasResources: !Equals
    - !Ref Quotas
    - true
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Cross-Account Role Configuration.  *Do Not Modify*"
        Parameters:
          - Core
          - Quotas
          - Spot0
          - RoleToAddPolicyTo
          - ExternalId
          - NotificationUrl
    ParameterLabels:
      ExternalID:
        default: "External ID"
Resources:
  # This is the cross account role that will be opearted by the Partner Solution
  CrossAccountRole:
    Properties:
      Description: DoiT International CMP
      RoleName: !Ref RoleToAddPolicyTo
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/AWSSavingsPlansReadOnlyAccess
        - arn:aws:iam::aws:policy/job-function/Billing
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::068664126052:root
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
            Sid: ""
        Version: "2012-10-17"
      Path: "/"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - "iam:List*"
                  - "iam:Get*"
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: PartnerAccess
    Type: "AWS::IAM::Role"
  Spot0Policy:
    Condition: CreateSpot0Resources
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "ec2:CreateLaunchTemplate"
              - "ec2:CreateLaunchTemplateVersion"
              - "autoscaling:BatchDeleteScheduledAction"
              - "autoscaling:BatchPutScheduledUpdateGroupAction"
              - "autoscaling:CreateOrUpdateTags"
              - "autoscaling:UpdateAutoScalingGroup"
              - "ec2:ModifyLaunchTemplate"
              - "ec2:RunInstances"
              - "autoscaling:Describe*"
              - "cloudformation:ListStacks"
              - "cloudformation:Describe*"
              - "ec2:Describe*"
              - "iam:PassRole"
            Resource: "*"
      Roles:
        - !Ref CrossAccountRole
  QuotasPolicy:
    Condition: CreateQuotasResources
    Type: AWS::IAM::ManagedPolicy
    Properties:
      # PolicyName: DoiT_Quotas_Policy-DO_NOT_DELETE
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "support:DescribeTrustedAdvisorCheckSummaries"
              - "support:DescribeTrustedAdvisorCheckRefreshStatuses"
              - "support:DescribeTrustedAdvisorChecks"
              - "support:DescribeSeverityLevels"
              - "support:RefreshTrustedAdvisorCheck"
              - "support:DescribeSupportLevel"
              - "support:DescribeCommunications"
              - "support:DescribeServices"
              - "support:DescribeIssueTypes"
              - "support:DescribeTrustedAdvisorCheckResult"
              - "trustedadvisor:DescribeNotificationPreferences"
              - "trustedadvisor:DescribeCheckRefreshStatuses"
              - "trustedadvisor:DescribeCheckItems"
              - "trustedadvisor:DescribeAccount"
              - "trustedadvisor:DescribeAccountAccess"
              - "trustedadvisor:DescribeChecks"
              - "trustedadvisor:DescribeCheckSummaries"
            Resource: "*"
      Roles:
        - !Ref CrossAccountRole
  NotificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt NotificationFunctionRole.Arn
      Handler: main
      Runtime: go1.x
      Timeout: 120
      Environment:
        Variables:
          NOTIFICATION_URL: !Ref NotificationUrl
          CUSTOMER_ID: !Ref ExternalId
      Code:
        S3Bucket: "doit-cmp-ops-pub"
        S3Key: main.zip
  version:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref NotificationFunction
  asyncconfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref NotificationFunction
      MaximumRetryAttempts: 0
      Qualifier: $LATEST
  NotificationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
  NotificationCall:
    Type: Custom::Notification
    Properties:
      ServiceToken: !GetAtt NotificationFunction.Arn
      ManagementArn: !GetAtt CrossAccountRole.Arn
    DependsOn:
      - NotificationFunctionRole
Outputs:
  RoleName:
    Value: !Ref CrossAccountRole
  RoleArn:
    Value: !GetAtt CrossAccountRole.Arn
