// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sdk "github.com/doitintl/insights/sdk"
)

// Insights is an autogenerated mock type for the Insights type
type Insights struct {
	mock.Mock
}

// PostInsightResults provides a mock function with given fields: ctx, results
func (_m *Insights) PostInsightResults(ctx context.Context, results []sdk.InsightResponse) error {
	ret := _m.Called(ctx, results)

	if len(ret) == 0 {
		panic("no return value specified for PostInsightResults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []sdk.InsightResponse) error); ok {
		r0 = rf(ctx, results)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInsights creates a new instance of Insights. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInsights(t interface {
	mock.TestingT
	Cleanup(func())
}) *Insights {
	mock := &Insights{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
