// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/doitintl/hello/scheduled-tasks/flexsaveresold/monitoring/domain"

	mock "github.com/stretchr/testify/mock"
)

// SharedPayerSavings is an autogenerated mock type for the SharedPayerSavings type
type SharedPayerSavings struct {
	mock.Mock
}

// DetectSharedPayerSavingsDiscrepancies provides a mock function with given fields: ctx, date
func (_m *SharedPayerSavings) DetectSharedPayerSavingsDiscrepancies(ctx context.Context, date string) (domain.SharedPayerSavingsDiscrepancies, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for DetectSharedPayerSavingsDiscrepancies")
	}

	var r0 domain.SharedPayerSavingsDiscrepancies
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.SharedPayerSavingsDiscrepancies, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.SharedPayerSavingsDiscrepancies); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SharedPayerSavingsDiscrepancies)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSharedPayerSavings creates a new instance of SharedPayerSavings. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSharedPayerSavings(t interface {
	mock.TestingT
	Cleanup(func())
}) *SharedPayerSavings {
	mock := &SharedPayerSavings{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
