// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/doitintl/hello/scheduled-tasks/common"

	mock "github.com/stretchr/testify/mock"

	"cloud.google.com/go/cloudtasks/apiv2/cloudtaskspb"
)

// CloudTask is an autogenerated mock type for the CloudTask type
type CloudTask struct {
	mock.Mock
}

// CreateCloudTask provides a mock function with given fields: ctx, config
func (_m *CloudTask) CreateCloudTask(ctx context.Context, config *common.CloudTaskConfig) (*cloudtaskspb.Task, error) {
	ret := _m.Called(ctx, config)

	var r0 *cloudtaskspb.Task
	if rf, ok := ret.Get(0).(func(context.Context, *common.CloudTaskConfig) *cloudtaskspb.Task); ok {
		r0 = rf(ctx, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudtaskspb.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *common.CloudTaskConfig) error); ok {
		r1 = rf(ctx, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
